spring.datasource.url=jdbc:postgresql://localhost:5432/unipass_db
spring.datasource.username=postgres
spring.datasource.password=your_password_here
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 30000 30 seconds, 86400000 one day, 1296000000 15 days
application.security.jwt.secret-key=28eb2dedfbaa7981a7eda0bf92cfca584c8ff526f57a695198d77b8dec994612
application.security.jwt.expiration=30000
application.security.jwt.refresh-token.expiration=1296000000